# @baseUrl = http://localhost
@baseUrl = http://localhost:9002
@id = 1

# Get all secrets
GET {{baseUrl}}/Secrets/GetSecrets
Accept: application/json

###

# Get a specific secret by ID
GET {{baseUrl}}/Secrets/GetSecret/{{id}}
Accept: application/json

###

# Post a new secret
POST {{baseUrl}}/Secrets/PostSecret
Content-Type: application/json

{
    "key": "New Secret",
    "value": "Secret Value"
}

###

# Update an existing secret
PUT {{baseUrl}}/Secrets/PutSecret?id={{id}}
Content-Type: application/json

{
    "key": "Updated Secret",
    "value": "Updated Value"
}

###

# Delete a secret
DELETE {{baseUrl}}/Secrets/DeleteSecret?id={{id}}
Accept: application/json