# @baseUrl = http://localhost
@baseUrl = http://localhost:9002
@id = 1
@key = DummyKey

# Get all secrets
GET {{baseUrl}}/Secrets/GetSecrets
Accept: application/json

###

# Get a specific secret by Key
GET {{baseUrl}}/Secret/{{key}}
Accept: application/json

###

# Get a specific secret by ID
GET {{baseUrl}}/Secrets/GetSecretById/{{id}}
Accept: application/json

###

# Post a new secret
POST {{baseUrl}}/Secrets/PostSecret
Content-Type: application/json

{
    "key": "{{$guid}}",
    "value": "Secret Value"
}

###

# Update an existing secret
PUT {{baseUrl}}/Secrets/PutSecret/{{id}}
Content-Type: application/json

{
    "key": "{{$guid}}",
    "value": "Updated Value"
}

###

# Delete a secret
DELETE {{baseUrl}}/Secrets/DeleteSecret/{{id}}
Accept: application/json