version: '3.8'

services:
  secret:
    build:
      context: ./secret
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}_web"
    ports:
      - "9002:80" # Temporary port for testing
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./secret/bin:/app
    networks:
      - secret_network

  postgres:
    image: postgres:13.3
    container_name: "${PROJECT_NAME}_postgres"
    # ports:
    #   - "5432:5432" # Temporary port for testing
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password123!
      - POSTGRES_DB=my_secrets_manager_db
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - ./../resources/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: "${PROJECT_NAME}_pgadmin"
    ports:
      - "9003:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@sample.com
      - PGADMIN_DEFAULT_PASSWORD=Password123!
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json

networks:
  secret_network:
    external: true
