name: deploy

on:
  push:
    # branches:
    #   - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Publish with dotnet
      run: dotnet publish --configuration Release Web/Web.csproj

    # - name: Archive build artifact
    #   run: |
    #     cd Web/bin/Release/net8.0
    #     7z a -tzip ${{ runner.temp }}\WindowsFormsApp1.zip *

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: Secret
        # path: ${{ runner.temp }}\WindowsFormsApp1.zip
        path: Web/bin/Release/net8.0